name: wazi_mobile_pos
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  scoped_model: ^1.0.1
  charts_flutter: ^0.5.0
  percent_indicator: ^1.0.12
  contacts_service: ^0.0.9
  simple_permissions: ^0.1.9
  firebase_core: ^0.2.5  # add dependency for Firebase Core
  firebase_auth: ^0.6.6
  diagonal: ^1.0.1
  keyboard_actions: ^1.0.3
  flutter_swiper: ^1.1.4
  google_sign_in: ^3.2.4
  carousel_pro: ^0.0.13
  cloud_firestore: ^0.8.2+3
  json_annotation: ^2.0.0
  uuid: ^1.0.3
  progress_hud: ^1.1.0
  localstorage: ^1.0.0
  image_picker: ^0.4.5
  firebase_storage: ^1.0.4
  flutter_image_compress: ^0.2.3
  path_provider: ^0.4.1
  intl: ^0.15.7
  flutter_launcher_icons: "^0.6.1"




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"
  build_runner: ^1.0.0
  json_serializable: ^2.0.0


flutter_icons:
  image_path: "icon/icon.png" 
  android: true
  ios: true
  
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lf_logo.png
    - assets/logo.png
    - assets/lf_logo_title.png
    - assets/bg_portrait.jpg
    - assets/brandon.png
    - assets/lf_name.png
    - assets/merchant1.png
    - assets/pointofsale.png
    - assets/merchanticon.png
    - assets/tillpoint.png
    - assets/tillpoint2.png
    - assets/inventory.png
    - assets/customers.png
    - assets/reporting.png
    - assets/staffmanagement.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald/Oswald-Bold.ttf
          weight: 700
    #  - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
